### PR TITLE
Improve docs' appearance in high-contrast mode

### LINKED ISSUE #169: Docs A11y: Docs could use some forced colors/High Contrast Mode tweaks
This doesn't quite fit into any docs templates, but I was poking around the site in High Contrast Mode, and I noticed that while overall the site is very strong in high-contrast mode, there are a few places here and there with room for improvement. Namely, anytime we rely on box-shadows and background-images, those are annihilated by High Contrast Mode.

For more info: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/forced-colors

### PR DESCRIPTION
**Pull request by BenDMyers**
Howdy! Got another accessibility PR for you!

This pull request introduces a few improvements for the design of the page in forced colors mode (namely, Windows High Contrast Mode). Overall, your site is really solid by default in Windows High Contrast Mode. All I really needed to do was go in and make sure that, for instance, box shadows had a forced colors equivalent.

To learn a little bit about forced colors, see https://developer.mozilla.org/en-US/docs/Web/CSS/@media/forced-colors

Resolves #169

### CODE REVIEW

**Comment by nachtfunke** [comment]
I can't test this on windows - so this might actually look different in an _actual_ high contrast mode. but if emulate forced colors via the dev tools, I see that edges of elements are missing because backgrounds are disappearing, that makes many of the elements basically float around:
Screenshot 2022-02-09 at 22 02 23
Screenshot 2022-02-09 at 22 02 34
Screenshot 2022-02-09 at 22 02 46
I wonder if it would make sense here, to add some borders around the padded elements instead. But then again, this might not be useful in high contrast mode. What do you think?

**Comment by BenDMyers** [comment]
@nachtfunke I'm totally game for that — and I did similar when I improved forced colors support on my personal site. I think it makes sense for things that are definitively containers, especially when they're adjacent to other containers that could all feel mixed up! I'm hesitant to overuse that in case the experience becomes too cluttered. It'd be great to come up with a solid list of things that could _definitely_ benefit from borders.

**Comment by nachtfunke** [comment]
> @nachtfunke I'm totally game for that — and I did similar when I improved forced colors support on my personal site. I think it makes sense for things that are definitively containers, especially when they're adjacent to other containers that could all feel mixed up! I'm hesitant to overuse that in case the experience becomes too cluttered. It'd be great to come up with a solid list of things that could _definitely_ benefit from borders.

I think on the docs end side of it, it'd be enough to just set a border around the navigation:
Screenshot 2022-02-09 at 22 33 41
In this example I also removed the padding entirely from the actual content, that makes it align correctly with everything again.

Other than that, I think the blockquotes make sense:
Screenshot 2022-02-09 at 22 34 05
They already use `infoBackground` on the left, so we could just  draw a border with this color too.

**Review by Holben888 — APPROVED** [review]
Contrastic!

**Pull request merged**
