### PR TITLE
Fix 0.5.0 error requiring react-dom, react as deps

### LINKED ISSUE #187: slinkity 0.5.0 drags in react-dom as a dependency even if you don't use it
I had a project running fine and after running npm update (to grab slinkity 0.5.0) I encountered the following.

npm start

```
package.json
...
"start": "BUILD='development' slinkity --serve --incremental",

```

Yielded the following error
```

...
Pre-bundling dependencies:
  @andystevenson/theme-toggle
  slinkity/client
(this will be run only when your dependencies or config have changed)
✘ [ERROR] Could not resolve "react-dom"

    node_modules/slinkity/client/renderer.js:2:21:
      2 │ import ReactDOM from 'react-dom'
        ╵                      ~~~~~~~~~~~

  You can mark the path "react-dom" as external to exclude it from the bundle, which will remove
  this error.
....

[11ty] Copied 25 files / Wrote 10 files in 0.75 seconds (75.0ms each, v1.0.0)
[11ty] Unhandled rejection in promise: (more in DEBUG output)
[11ty] > Build failed with 1 error:
node_modules/slinkity/client/renderer.js:2:21: ERROR: Could not resolve "react-dom"

`Error` was thrown:
[11ty]     Error: Build failed with 1 error:
    node_modules/slinkity/client/renderer.js:2:21: ERROR: Could not resolve "react-dom"


```

Obviously didn't expect the crash.
I am using slinkity to build a pure eleventy/vite site not using react or any other framework.

Vite now drags in the following dependencies.
```

  slinkity/client
  react
  react/jsx-runtime
  react/jsx-dev-runtime
  (...and 1 more)
```

Which aren't used anywhere in my code.

### PR DESCRIPTION
**Pull request by smithbm2316**
This should resolve #187 as @Holben888 suggested to try. I'll confirm that this alone actually ends up fixing the issue later today when I get back home, but wanted to get the PR with the fix up ASAP so I don't forget about making this contribution. Thanks Ben for all of your hard work on Slinkity and extremely informative videos that you've made on partial hydration, custom client-side routing without a SPA framework, etc! I really like the approach Slinkity uses and am excited to try and start hacking on the updates to my personal portfolio site that I've been wanting to make for years now 😃 (and from one Ben to another, you've got a solid first name 😎)

### CODE REVIEW

**Comment by Holben888** [comment]
Ack, might be work running `pnpm link:fix` to resolve this lint issues. Just confirmed this is working on my end though. And from one Ben to another... thank you so much for the support 😁

**Comment by smithbm2316** [comment]
Oh of course that's what I get for making this PR all through the Github editor and not setting up the project locally 🤦🏻‍♂️ I think the lint issue should be fixed now!

**Review by Holben888 — APPROVED** [review]
`dep`initely optimized 👏

**Comment by smithbm2316** [comment]
Thanks for your extremely detailed instructions and feedback Ben! This was the easiest open-source contribution I think I'll ever make 😂

**Comment by Holben888** [comment]
Hey, if there's more words than actual lines committed... we're doing open source right ❤️

**Pull request merged**
